// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class AssignPropertyToEntityRequest
{
    public Guid Id { get; set; }

    public Guid SessionId { get; set; }

    public long UnixTime { get; set; }

    public Guid PropertyId { get; set; }

    public Guid EntityId { get; set; }

    public DateTime DateTime { get; set; }

    //public virtual AssignInfoPropertyToEntityCategoryRequest IdNavigation { get; set; }
}