// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class AssignInfoPropertyToEntityCategoryRequest
{
    public Guid Id { get; set; }

    public Guid ChannelId { get; set; }

    public string Iv { get; set; }

    public string EncryptedPayload { get; set; }

    public string Type { get; set; }

    public DateTime DateTime { get; set; }

    public virtual AssignPropertyToEntityRequest AssignPropertyToEntityRequest { get; set; }
}