// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class Audit
{
    public int id { get; set; }
    public string action { get; set; }
    public string tableName { get; set; }
    public Guid recordId { get; set; }
    public string parameter { get; set; }
    public string fromValue { get; set; }
    public string toValue { get; set; }
    public string performedBy { get; set; }
    public DateTime dateTime { get; set; }
}