// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class ChannelLoginProperty
{
    public Guid Id { get; set; }

    public Guid IdentificationChannelId { get; set; }

    public Guid PropertyId { get; set; }

    public virtual IdentificationChannel IdentificationChannel { get; set; }

    public virtual Property Property { get; set; }
}