// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class ChannelEntity
{
    public Guid Id { get; set; }

    public Guid IdentificationChannelId { get; set; }

    public Guid EntityId { get; set; }

    public bool EditAccess { get; set; }

    public virtual Entity Entity { get; set; }

    public virtual IdentificationChannel IdentificationChannel { get; set; }
}