// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace eLogin.Models;

public partial class CreateInfoPropertyResponse
{
    [JsonIgnore]
    public Guid Id { get; set; }

    [JsonIgnore]
    public Guid RequestId { get; set; }

    public bool IsSuccess { get; set; }

    public string FailureReason { get; set; }

    public Guid? PropertyId { get; set; }

    public DateTime DateTime { get; set; }
}