// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class CustomerEntityInstance
{
    public Guid Id { get; set; }

    public string EntityInstanceName { get; set; }

    public Guid CategoryId { get; set; }

    public string CategoryName { get; set; }

    public Guid? ParentEntityCategoryId { get; set; }

    public virtual List<EntityInstancePropertyValue> entityInstancePropertyValues { get; set; }
}