// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class CustomerPassword
{
    public Guid Id { get; set; }

    public string Password { get; set; }

    public DateTime CreationDateTime { get; set; }

    public bool IsExpired { get; set; }

    public DateTime? ExpiryDateTime { get; set; }

    public string ExpiredBy { get; set; }

    public Guid CustomerId { get; set; }

    public Guid IdentificationChannelId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual IdentificationChannel IdentificationChannel { get; set; }
}