// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace eLogin.Models;

public partial class Customer
{
    public Guid Id { get; set; }
    public bool IsLocked { get; set; }

    [JsonIgnore]
    public bool IsDeleted { get; set; }


    public virtual List<CustomerInfoValue> CustomerInfoValues { get; set; }
    public virtual List<EntityInstance> EntitieInstances { get; set; }
    public virtual List<CustomerLoginAttempt> CustomerLoginAttempts { get; set; }
    public virtual List<CustomerPassword> CustomerPasswords { get; set; }
}