// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class CustomerLoginAttempt
{
    public Guid Id { get; set; }

    public bool IsSuccess { get; set; }

    public bool IncorrectPassword { get; set; }

    public bool IsExpired { get; set; }

    public bool LockedAccount { get; set; }

    public DateTime DateTime { get; set; }

    public Guid CustomerId { get; set; }

    public Guid IdentificationChannelId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual IdentificationChannel IdentificationChannel { get; set; }
}