// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class CustomerInfoValue
{
    public Guid Id { get; set; }

    public string Value { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CustomerId { get; set; }

    public Guid EntityInstanceId { get; set; }

    public Guid PropertyId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual EntityInstance EntityInstance { get; set; }

    public virtual Property Property { get; set; }
}