// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class DeleteEntityCategoryRequest
{
    public Guid Id { get; set; }

    public Guid ChannelId { get; set; }

    public string Iv { get; set; }

    public string EncryptedPayload { get; set; }

    public string Type { get; set; }

    public Guid SessionId { get; set; }

    public long UnixTime { get; set; }

    public Guid EntityCategoryId { get; set; }

    public DateTime? DateTime { get; set; }

    public DateTime RequestDeleteEntityCategoryRequestDateTime { get; set; }
}