// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text.Json.Serialization;

namespace eLogin.Models;

public partial class EntityCategory
{
    public Guid Id { get; set; }
    [DisplayName("Category Name")]
    public string CategoryName { get; set; }

    [DisplayName("Parent Category")]
    public Guid? ParentEntityCategoryId { get; set; }
    public virtual EntityCategory ParentEntityCategory { get; set; }

    [JsonIgnore]
    public bool IsDeleted { get; set; }


    public virtual List<Entity> Entities { get; set; }
    public virtual List<EntityCategory> ChildEntityCategories { get; set; }
}