// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class EntityInstancePropertyValue
{
    public Guid Id { get; set; }

    public Guid CustomerInfoValueId { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

    public Guid CustomerEntityInstanceId { get; set; }

    public virtual CustomerEntityInstance CustomerEntityInstance { get; set; }
}