// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class Entity
{
    public Guid Id { get; set; }

    public string EntityName { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsRequired { get; set; }

    public Guid EntityCategoryId { get; set; }

    public virtual ICollection<ChannelEntity> ChannelEntities { get; set; } = new List<ChannelEntity>();

    public virtual EntityCategory EntityCategory { get; set; }

    public virtual ICollection<EntityInstance> EntityInstances { get; set; } = new List<EntityInstance>();

    public virtual ICollection<EntityProperty> EntityProperties { get; set; } = new List<EntityProperty>();

    public virtual ICollection<IdentificationChannel> IdentificationChannels { get; set; } = new List<IdentificationChannel>();
}