// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class EntityInstance
{
    public Guid Id { get; set; }

    public string EntityInstanceName { get; set; }

    public bool IsDeleted { get; set; }

    public Guid CustomerId { get; set; }

    public Guid EntityId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<CustomerInfoValue> CustomerInfoValues { get; set; } = new List<CustomerInfoValue>();

    public virtual Entity Entity { get; set; }
}