// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace eLogin.Models;

public partial class GetEntitiesRequest
{
    public Guid Id { get; set; }

    [Required]
    public Guid SessionId { get; set; }

    [Required]
    public long UnixTime { get; set; }

    public DateTime DateTime { get; set; }
}