// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class IdentificationChannel
{
    public Guid Id { get; set; }

    public string Channel { get; set; }

    public string Key { get; set; }

    public bool IsEnabled { get; set; }

    public string PasswordValidationRegex { get; set; }

    public string PasswordValidationHint { get; set; }

    public int PasswordValidityDays { get; set; }

    public Guid DefaultIdentifierEntityId { get; set; }

    public Guid DefaultIdentifierPropertyId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ChannelEntity> ChannelEntities { get; set; } = new List<ChannelEntity>();

    public virtual ICollection<ChannelLoginProperty> ChannelLoginProperties { get; set; } = new List<ChannelLoginProperty>();

    public virtual ICollection<CustomerLoginAttempt> CustomerLoginAttempts { get; set; } = new List<CustomerLoginAttempt>();

    public virtual ICollection<CustomerPassword> CustomerPasswords { get; set; } = new List<CustomerPassword>();

    public virtual Entity DefaultIdentifierEntity { get; set; }

    public virtual Property DefaultIdentifierProperty { get; set; }

    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();
}