// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class MatchingCustomer
{
    public Guid Id { get; set; }

    public bool IsLocked { get; set; }

    public Guid SearchCustomerResponseId { get; set; }

    public virtual ICollection<CustomerEntityInstance> CustomerEntityInstances { get; set; } = new List<CustomerEntityInstance>();

    public virtual SearchCustomerResponse1 SearchCustomerResponse { get; set; }
}