// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using eLogin.Models.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace eLogin.Models;


public class PasswordHistory
{
    public Guid Id { get; set; }

    [Required]
    public Guid UserId { get; set; }

    public virtual User User { get; set; }

    [Required]
    public string PasswordHash { get; set; }

    public DateTime DateCreated { get; set; }

}
