// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class PasswordSettings
{
    public int Id { get; set; }
    public int PasswordExpirationDays { get; set; }
    public int PasswordHistoryLimit { get; set; }

}