// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class ResponseCreateEntityCategoryResponse
{
    public Guid Id { get; set; }

    public Guid RequestId { get; set; }

    public string Iv { get; set; }

    public string EncryptedPayload { get; set; }

    public DateTime DateTime { get; set; }

    public virtual CreateEntityCategoryResponse1 CreateEntityCategoryResponse1 { get; set; }
}