// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class SearchCustomerResponse1
{
    public Guid Id { get; set; }

    public Guid RequestId { get; set; }

    public string RequestType { get; set; }

    public bool IsSuccess { get; set; }

    public string FailureReason { get; set; }

    public DateTime DateTime { get; set; }

    //public virtual ResponseSearchCustomerResponse IdNavigation { get; set; }

    public virtual ICollection<MatchingCustomer> MatchingCustomers { get; set; } = new List<MatchingCustomer>();
}