// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class SystemSetting
{
    public Guid Id { get; set; }

    public string SettingName { get; set; }

    public string Value { get; set; }
}