// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace eLogin.Models;

public partial class UserSession
{
    public Guid Id { get; set; }

    public string Identifier { get; set; }

    public string Action { get; set; }

    public DateTime TimeStamp { get; set; }
}